### PR TITLE
Software requirements

### PR DESCRIPTION
**Pull request by jeremywbrazell**

### CODE REVIEW

**Review by fadnesscharlie — DISMISSED** [review]
I approve

**Review by fadnesscharlie — DISMISSED** [review]
I approve

**Review by vbchomp — DISMISSED** [review]
needs to merge into the sw reqs.

**Review by vbchomp — DISMISSED** [review]
Please publish

**Review by fadnesscharlie — APPROVED** [review]

**Review by MuckT — APPROVED** [review]

**Pull request merged**
